services:
  postgres_test:
    image: postgres:16
    environment:
      POSTGRES_USER: smr
      POSTGRES_PASSWORD: smr_pass
      POSTGRES_DB: smart_meeting_room_test
    ports:
      - "5434:5432"  # separate host port for test DB
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smr -d smart_meeting_room_test"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata_test:
