services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: smr
      POSTGRES_PASSWORD: smr_pass
      POSTGRES_DB: smart_meeting_room
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smr"]
      interval: 5s
      timeout: 3s
      retries: 5

  users_service:
    build: ./services/users_service
    environment:
      POSTGRES_USER: smr
      POSTGRES_PASSWORD: smr_pass
      POSTGRES_DB: smart_meeting_room
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      JWT_SECRET: devsecret
    depends_on:
      - postgres
    ports:
      - "8001:8000"

volumes:
  pgdata: