services:
  postgres:
    image: postgres:16
    # If on ARM and see exec format errors again, uncomment next line:
    # platform: linux/amd64
    environment:
      POSTGRES_USER: smr
      POSTGRES_PASSWORD: smr_pass
      POSTGRES_DB: smart_meeting_room
      TZ: Africa/Cairo
      PGTZ: Africa/Cairo
    ports:
      - "5433:5432"  # changed host port to avoid local conflict
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smr -d smart_meeting_room"]
      interval: 5s
      timeout: 3s
      retries: 5

  users_service:
    build:
      context: .
      dockerfile: services/users_service/Dockerfile
    environment:
      POSTGRES_USER: smr
      POSTGRES_PASSWORD: smr_pass
      POSTGRES_DB: smart_meeting_room
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      JWT_SECRET: devsecret
      PORT: 8000
    depends_on:
      - postgres
    ports:
      - "8001:8000"

  rooms_service:
    build:
      context: .
      dockerfile: services/rooms_service/Dockerfile
    environment:
      POSTGRES_USER: smr
      POSTGRES_PASSWORD: smr_pass
      POSTGRES_DB: smart_meeting_room
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      PORT: 8002
    depends_on:
      - postgres
    ports:
      - "8002:8002"

  bookings_service:
    build:
      context: .
      dockerfile: services/bookings_service/Dockerfile
    environment:
      POSTGRES_USER: smr
      POSTGRES_PASSWORD: smr_pass
      POSTGRES_DB: smart_meeting_room
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      PORT: 8003
      USE_HTTP_VALIDATION: "1"
    depends_on:
      - postgres
    ports:
      - "8003:8003"

  reviews_service:
    build:
      context: .
      dockerfile: services/reviews_service/Dockerfile
    environment:
      POSTGRES_USER: smr
      POSTGRES_PASSWORD: smr_pass
      POSTGRES_DB: smart_meeting_room
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      PORT: 8004
    depends_on:
      - postgres
    ports:
      - "8004:8004"

volumes:
  pgdata: